
import { createStyledIcon } from './iconUtils';
import {
  Apple, Banana, Beer, Beef, Cake, CircleAlert, Carrot, Cherry, Coffee, Cookie, Croissant, Droplet,
  Drumstick, Egg, Fish, IceCream, Milk, Pizza, Salad, Sandwich, Wine, Box, Trash,
  ChevronDown, Filter, FlaskConical, Circle, Grape, Bookmark, BowlFood, ChefHat, Package,
  QrCode, Heart, CircleDot, Cloud, Soup, Wheat, Flower, Cog, Crown, Map,
  Diamond, Donut, Droplets, EggFried, Eye, Hamburger, FilterX, Ship, FolderIcon,
  Snowflake, Sprout, Citrus, Bean, Leaf, Flame, Glasses, Globe, Users,
  Layers, Timer, Car, UtensilsCrossed, Store, Candy, Dumbbell, Martini,
  PieChart, Plant, Shrimp, Radio, ShoppingBag, ShoppingCart, Star, 
  LampFloor, Table, Bottle, Headphones, Tooth, Hat, Pumpkin, ZoomIn
} from "lucide-react";

export type IconOption = {
  value: string;
  label: string;
  icon: React.ReactElement;
  shelfLife: number; // Default shelf life in days
};

// Define all possible icons - sorted alphabetically
export const ALL_ICONS: Record<string, IconOption> = {
  apple: { value: 'apple', label: 'Apple', icon: createStyledIcon(Apple), shelfLife: 14 },
  avocado: { value: 'avocado', label: 'Avocado', icon: createStyledIcon(Apple), shelfLife: 5 },
  bacon: { value: 'bacon', label: 'Bacon', icon: createStyledIcon(Beef), shelfLife: 7 },
  baguette: { value: 'baguette', label: 'Baguette', icon: createStyledIcon(Bookmark), shelfLife: 3 },
  banana: { value: 'banana', label: 'Banana', icon: createStyledIcon(Banana), shelfLife: 5 },
  bean: { value: 'bean', label: 'Beans', icon: createStyledIcon(Bean), shelfLife: 5 },
  beef: { value: 'beef', label: 'Beef', icon: createStyledIcon(Beef), shelfLife: 3 },
  beer: { value: 'beer', label: 'Beer', icon: createStyledIcon(Beer), shelfLife: 30 },
  box: { value: 'box', label: 'Generic', icon: createStyledIcon(Box), shelfLife: 7 },
  bread: { value: 'bread', label: 'Bread', icon: createStyledIcon(Bookmark), shelfLife: 5 },
  cake: { value: 'cake', label: 'Cake', icon: createStyledIcon(Cake), shelfLife: 5 },
  cake2: { value: 'cake2', label: 'Birthday Cake', icon: createStyledIcon(Cake), shelfLife: 4 },
  candy: { value: 'candy', label: 'Candy', icon: createStyledIcon(Candy), shelfLife: 180 },
  cardboardBox: { value: 'cardboardBox', label: 'Cardboard Box', icon: createStyledIcon(Package), shelfLife: 365 },
  carrot: { value: 'carrot', label: 'Carrot', icon: createStyledIcon(Carrot), shelfLife: 14 },
  cannedPumpkin: { value: 'cannedPumpkin', label: 'Canned Pumpkin', icon: createStyledIcon(Circle), shelfLife: 365 },
  cereal: { value: 'cereal', label: 'Cereal', icon: createStyledIcon(QrCode), shelfLife: 180 },
  cheese: { value: 'cheese', label: 'Cheese', icon: createStyledIcon(ChevronDown), shelfLife: 14 },
  chefHat: { value: 'chefHat', label: 'Chef Hat', icon: createStyledIcon(ChefHat), shelfLife: 7 },
  chefHat2: { value: 'chefHat2', label: 'Chef Hat (Alt)', icon: createStyledIcon(ChefHat), shelfLife: 7 },
  cherry: { value: 'cherry', label: 'Cherry', icon: createStyledIcon(Cherry), shelfLife: 7 },
  cherrySymbol: { value: 'cherrySymbol', label: 'Cherry Symbol', icon: createStyledIcon(Cherry), shelfLife: 7 },
  chili: { value: 'chili', label: 'Chili', icon: createStyledIcon(Heart), shelfLife: 7 },
  chocolateIcon: { value: 'chocolateIcon', label: 'Chocolate', icon: createStyledIcon(Eye), shelfLife: 180 },
  cinnamon: { value: 'cinnamon', label: 'Cinnamon', icon: createStyledIcon(Timer), shelfLife: 365 },
  coffee: { value: 'coffee', label: 'Coffee', icon: createStyledIcon(Coffee), shelfLife: 14 },
  coffeeBag: { value: 'coffeeBag', label: 'Coffee Bag', icon: createStyledIcon(Coffee), shelfLife: 30 },
  coffeeIcon: { value: 'coffeeIcon', label: 'Coffee Cup', icon: createStyledIcon(Coffee), shelfLife: 1 },
  container: { value: 'container', label: 'Container', icon: createStyledIcon(Box), shelfLife: 7 },
  cookieJar: { value: 'cookieJar', label: 'Cookie Jar', icon: createStyledIcon(Cookie), shelfLife: 14 },
  cookie: { value: 'cookie', label: 'Cookie', icon: createStyledIcon(Cookie), shelfLife: 7 },
  cloudCookie: { value: 'cloudCookie', label: 'Cloud Cookie', icon: createStyledIcon(Cookie), shelfLife: 7 },
  cookingPot: { value: 'cookingPot', label: 'Cooking Pot', icon: createStyledIcon(Soup), shelfLife: 5 },
  corn: { value: 'corn', label: 'Corn', icon: createStyledIcon(Wheat), shelfLife: 5 },
  cracker: { value: 'cracker', label: 'Cracker', icon: createStyledIcon(Sandwich), shelfLife: 30 },
  croissant: { value: 'croissant', label: 'Croissant', icon: createStyledIcon(Croissant), shelfLife: 3 },
  cupSoda: { value: 'cupSoda', label: 'Cup Soda', icon: createStyledIcon(Droplet), shelfLife: 1 },
  custard: { value: 'custard', label: 'Custard', icon: createStyledIcon(Bookmark), shelfLife: 5 },
  desertIcon: { value: 'desertIcon', label: 'Dessert', icon: createStyledIcon(Map), shelfLife: 5 },
  diningTable: { value: 'diningTable', label: 'Dining Table', icon: createStyledIcon(Table), shelfLife: 7 },
  donutIcon: { value: 'donutIcon', label: 'Donut', icon: createStyledIcon(Donut), shelfLife: 3 },
  drumstick: { value: 'drumstick', label: 'Chicken', icon: createStyledIcon(Drumstick), shelfLife: 3 },
  egg: { value: 'egg', label: 'Egg', icon: createStyledIcon(Egg), shelfLife: 30 },
  eggFried: { value: 'eggFried', label: 'Fried Egg', icon: createStyledIcon(EggFried), shelfLife: 1 },
  filter: { value: 'filter', label: 'Filter', icon: createStyledIcon(Filter), shelfLife: 30 },
  fish: { value: 'fish', label: 'Fish', icon: createStyledIcon(Fish), shelfLife: 2 },
  fishIcon: { value: 'fishIcon', label: 'Fish Icon', icon: createStyledIcon(Fish), shelfLife: 2 },
  flame: { value: 'flame', label: 'Flame', icon: createStyledIcon(Flame), shelfLife: 7 },
  flaskConical: { value: 'flaskConical', label: 'Flask', icon: createStyledIcon(FlaskConical), shelfLife: 7 },
  flour: { value: 'flour', label: 'Flour', icon: createStyledIcon(Wheat), shelfLife: 180 },
  fork: { value: 'fork', label: 'Fork', icon: createStyledIcon(UtensilsCrossed), shelfLife: 7 },
  fries: { value: 'fries', label: 'French Fries', icon: createStyledIcon(UtensilsCrossed), shelfLife: 1 },
  frozenIcon: { value: 'frozenIcon', label: 'Frozen Food', icon: createStyledIcon(Snowflake), shelfLife: 90 },
  garlic: { value: 'garlic', label: 'Garlic', icon: createStyledIcon(Circle), shelfLife: 90 },
  ginger: { value: 'ginger', label: 'Ginger', icon: createStyledIcon(Flower), shelfLife: 14 },
  gingerbreadCookie: { value: 'gingerbreadCookie', label: 'Gingerbread Cookie', icon: createStyledIcon(Cookie), shelfLife: 14 },
  glassWater: { value: 'glassWater', label: 'Glass Water', icon: createStyledIcon(Glasses), shelfLife: 1 },
  glassWine: { value: 'glassWine', label: 'Glass Wine', icon: createStyledIcon(Wine), shelfLife: 5 },
  grape: { value: 'grape', label: 'Grape', icon: createStyledIcon(Grape), shelfLife: 7 },
  grapeCluster: { value: 'grapeCluster', label: 'Grape Cluster', icon: createStyledIcon(Grape), shelfLife: 7 },
  grapefruit: { value: 'grapefruit', label: 'Grapefruit', icon: createStyledIcon(Citrus), shelfLife: 14 },
  greenBeans: { value: 'greenBeans', label: 'Green Beans', icon: createStyledIcon(Bean), shelfLife: 7 },
  greenOnion: { value: 'greenOnion', label: 'Green Onion', icon: createStyledIcon(Leaf), shelfLife: 7 },
  grocery: { value: 'grocery', label: 'Grocery', icon: createStyledIcon(Store), shelfLife: 7 },
  hamburger: { value: 'hamburger', label: 'Hamburger', icon: createStyledIcon(Hamburger), shelfLife: 1 },
  ham: { value: 'ham', label: 'Ham', icon: createStyledIcon(Beef), shelfLife: 7 },
  herbIcon: { value: 'herbIcon', label: 'Herb', icon: createStyledIcon(Heart), shelfLife: 7 },
  herbs: { value: 'herbs', label: 'Herbs', icon: createStyledIcon(Leaf), shelfLife: 7 },
  honey: { value: 'honey', label: 'Honey', icon: createStyledIcon(Heart), shelfLife: 365 },
  hotDog: { value: 'hotDog', label: 'Hot Dog', icon: createStyledIcon(Sandwich), shelfLife: 1 },
  hotIcon: { value: 'hotIcon', label: 'Hot', icon: createStyledIcon(Flame), shelfLife: 7 },
  hotSauce: { value: 'hotSauce', label: 'Hot Sauce', icon: createStyledIcon(Heart), shelfLife: 180 },
  iceCream: { value: 'iceCream', label: 'Ice Cream', icon: createStyledIcon(IceCream), shelfLife: 14 },
  iceCreamCone: { value: 'iceCreamCone', label: 'Ice Cream Cone', icon: createStyledIcon(IceCream), shelfLife: 1 },
  iceCreamScoop: { value: 'iceCreamScoop', label: 'Ice Cream Scoop', icon: createStyledIcon(IceCream), shelfLife: 14 },
  iceCreamShake: { value: 'iceCreamShake', label: 'Ice Cream Shake', icon: createStyledIcon(Martini), shelfLife: 1 },
  icePop: { value: 'icePop', label: 'Ice Pop', icon: createStyledIcon(IceCream), shelfLife: 180 },
  jam: { value: 'jam', label: 'Jam', icon: createStyledIcon(Circle), shelfLife: 30 },
  jarIcon: { value: 'jarIcon', label: 'Jar', icon: createStyledIcon(Car), shelfLife: 30 },
  jello: { value: 'jello', label: 'Jello', icon: createStyledIcon(Soup), shelfLife: 7 },
  jug: { value: 'jug', label: 'Jug', icon: createStyledIcon(Coffee), shelfLife: 7 },
  kebab: { value: 'kebab', label: 'Kebab', icon: createStyledIcon(UtensilsCrossed), shelfLife: 1 },
  kettle: { value: 'kettle', label: 'Kettle', icon: createStyledIcon(Soup), shelfLife: 7 },
  ketchup: { value: 'ketchup', label: 'Ketchup', icon: createStyledIcon(Circle), shelfLife: 180 },
  kiwi: { value: 'kiwi', label: 'Kiwi', icon: createStyledIcon(Cherry), shelfLife: 7 },
  knife: { value: 'knife', label: 'Knife', icon: createStyledIcon(Circle), shelfLife: 7 },
  lemon: { value: 'lemon', label: 'Lemon', icon: createStyledIcon(Circle), shelfLife: 14 },
  lemonSlice: { value: 'lemonSlice', label: 'Lemon Slice', icon: createStyledIcon(Circle), shelfLife: 3 },
  lettuce: { value: 'lettuce', label: 'Lettuce', icon: createStyledIcon(Salad), shelfLife: 7 },
  lime: { value: 'lime', label: 'Lime', icon: createStyledIcon(Timer), shelfLife: 14 },
  lobster: { value: 'lobster', label: 'Lobster', icon: createStyledIcon(Fish), shelfLife: 1 },
  macaron: { value: 'macaron', label: 'Macaron', icon: createStyledIcon(Cookie), shelfLife: 5 },
  mandarin: { value: 'mandarin', label: 'Mandarin', icon: createStyledIcon(Circle), shelfLife: 14 },
  mango: { value: 'mango', label: 'Mango', icon: createStyledIcon(Circle), shelfLife: 5 },
  market: { value: 'market', label: 'Market', icon: createStyledIcon(Store), shelfLife: 7 },
  marshmallow: { value: 'marshmallow', label: 'Marshmallow', icon: createStyledIcon(Candy), shelfLife: 180 },
  melon: { value: 'melon', label: 'Melon', icon: createStyledIcon(Circle), shelfLife: 7 },
  milk: { value: 'milk', label: 'Milk', icon: createStyledIcon(Milk), shelfLife: 7 },
  milkBottle: { value: 'milkBottle', label: 'Milk Bottle', icon: createStyledIcon(Milk), shelfLife: 7 },
  mint: { value: 'mint', label: 'Mint', icon: createStyledIcon(FilterX), shelfLife: 5 },
  mintLeaf: { value: 'mintLeaf', label: 'Mint Leaf', icon: createStyledIcon(Flower), shelfLife: 5 },
  mixingBowl: { value: 'mixingBowl', label: 'Mixing Bowl', icon: createStyledIcon(UtensilsCrossed), shelfLife: 7 },
  muffin: { value: 'muffin', label: 'Muffin', icon: createStyledIcon(Candy), shelfLife: 5 },
  mushroom: { value: 'mushroom', label: 'Mushroom', icon: createStyledIcon(Circle), shelfLife: 7 },
  nut: { value: 'nut', label: 'Nut', icon: createStyledIcon(Circle), shelfLife: 180 },
  oats: { value: 'oats', label: 'Oats', icon: createStyledIcon(Wheat), shelfLife: 365 },
  oil: { value: 'oil', label: 'Oil', icon: createStyledIcon(Circle), shelfLife: 365 },
  olive: { value: 'olive', label: 'Olive', icon: createStyledIcon(Citrus), shelfLife: 14 },
  oliveOil: { value: 'oliveOil', label: 'Olive Oil', icon: createStyledIcon(Circle), shelfLife: 365 },
  onion: { value: 'onion', label: 'Onion', icon: createStyledIcon(CircleDot), shelfLife: 30 },
  orange: { value: 'orange', label: 'Orange', icon: createStyledIcon(Circle), shelfLife: 14 },
  orangeSlice: { value: 'orangeSlice', label: 'Orange Slice', icon: createStyledIcon(Circle), shelfLife: 3 },
  pancake: { value: 'pancake', label: 'Pancake', icon: createStyledIcon(Pizza), shelfLife: 1 },
  pancakes: { value: 'pancakes', label: 'Pancakes Stack', icon: createStyledIcon(Layers), shelfLife: 1 },
  paprika: { value: 'paprika', label: 'Paprika', icon: createStyledIcon(Flower), shelfLife: 365 },
  pasta: { value: 'pasta', label: 'Pasta', icon: createStyledIcon(Circle), shelfLife: 365 },
  pastaIcon: { value: 'pastaIcon', label: 'Pasta Icon', icon: createStyledIcon(Sandwich), shelfLife: 365 },
  peach: { value: 'peach', label: 'Peach', icon: createStyledIcon(Circle), shelfLife: 5 },
  pear: { value: 'pear', label: 'Pear', icon: createStyledIcon(Circle), shelfLife: 7 },
  pearIcon: { value: 'pearIcon', label: 'Pear Icon', icon: createStyledIcon(Circle), shelfLife: 7 },
  pepper: { value: 'pepper', label: 'Pepper', icon: createStyledIcon(Circle), shelfLife: 365 },
  pepperShaker: { value: 'pepperShaker', label: 'Pepper Shaker', icon: createStyledIcon(Circle), shelfLife: 365 },
  peppermint: { value: 'peppermint', label: 'Peppermint', icon: createStyledIcon(Flower), shelfLife: 7 },
  pickleJar: { value: 'pickleJar', label: 'Pickle Jar', icon: createStyledIcon(Package), shelfLife: 30 },
  pie: { value: 'pie', label: 'Pie', icon: createStyledIcon(Circle), shelfLife: 5 },
  pieIcon: { value: 'pieIcon', label: 'Pie Icon', icon: createStyledIcon(PieChart), shelfLife: 5 },
  pineapple: { value: 'pineapple', label: 'Pineapple', icon: createStyledIcon(Circle), shelfLife: 7 },
  pizza: { value: 'pizza', label: 'Pizza', icon: createStyledIcon(Pizza), shelfLife: 3 },
  pizzaSlice: { value: 'pizzaSlice', label: 'Pizza Slice', icon: createStyledIcon(Pizza), shelfLife: 3 },
  plant: { value: 'plant', label: 'Plant', icon: createStyledIcon(Sprout), shelfLife: 7 },
  plant2: { value: 'plant2', label: 'Plant 2', icon: createStyledIcon(Plant), shelfLife: 7 },
  plantPot: { value: 'plantPot', label: 'Plant Pot', icon: createStyledIcon(Flower), shelfLife: 7 },
  plum: { value: 'plum', label: 'Plum', icon: createStyledIcon(Cherry), shelfLife: 5 },
  popcorn: { value: 'popcorn', label: 'Popcorn', icon: createStyledIcon(Circle), shelfLife: 7 },
  popsicle: { value: 'popsicle', label: 'Popsicle', icon: createStyledIcon(Circle), shelfLife: 7 },
  pot: { value: 'pot', label: 'Pot', icon: createStyledIcon(Soup), shelfLife: 7 },
  potIcon: { value: 'potIcon', label: 'Pot Icon', icon: createStyledIcon(Soup), shelfLife: 7 },
  potato: { value: 'potato', label: 'Potato', icon: createStyledIcon(CircleDot), shelfLife: 30 },
  potatoes: { value: 'potatoes', label: 'Potatoes', icon: createStyledIcon(CircleDot), shelfLife: 30 },
  prawn: { value: 'prawn', label: 'Prawn', icon: createStyledIcon(Shrimp), shelfLife: 2 },
  pretzel: { value: 'pretzel', label: 'Pretzel', icon: createStyledIcon(Circle), shelfLife: 5 },
  protein: { value: 'protein', label: 'Protein', icon: createStyledIcon(Dumbbell), shelfLife: 30 },
  proteinShake: { value: 'proteinShake', label: 'Protein Shake', icon: createStyledIcon(Martini), shelfLife: 1 },
  pumpkin: { value: 'pumpkin', label: 'Pumpkin', icon: createStyledIcon(Pumpkin), shelfLife: 30 },
  pumpkinIcon: { value: 'pumpkinIcon', label: 'Pumpkin Icon', icon: createStyledIcon(Pumpkin), shelfLife: 30 },
  radish: { value: 'radish', label: 'Radish', icon: createStyledIcon(CircleDot), shelfLife: 14 },
  recipeBox: { value: 'recipeBox', label: 'Recipe Box', icon: createStyledIcon(Dumbbell), shelfLife: 7 },
  restaurant: { value: 'restaurant', label: 'Restaurant', icon: createStyledIcon(UtensilsCrossed), shelfLife: 7 },
  rice: { value: 'rice', label: 'Rice', icon: createStyledIcon(Wheat), shelfLife: 365 },
  riceBall: { value: 'riceBall', label: 'Rice Ball', icon: createStyledIcon(Sandwich), shelfLife: 1 },
  riceBowl: { value: 'riceBowl', label: 'Rice Bowl', icon: createStyledIcon(Soup), shelfLife: 1 },
  rum: { value: 'rum', label: 'Rum', icon: createStyledIcon(Martini), shelfLife: 365 },
  sage: { value: 'sage', label: 'Sage', icon: createStyledIcon(Flower), shelfLife: 7 },
  salad: { value: 'salad', label: 'Salad', icon: createStyledIcon(Salad), shelfLife: 5 },
  salt: { value: 'salt', label: 'Salt', icon: createStyledIcon(Circle), shelfLife: 1825 },
  saltShaker: { value: 'saltShaker', label: 'Salt Shaker', icon: createStyledIcon(Circle), shelfLife: 1825 },
  salmon: { value: 'salmon', label: 'Salmon', icon: createStyledIcon(Fish), shelfLife: 3 },
  sandwich: { value: 'sandwich', label: 'Sandwich', icon: createStyledIcon(Sandwich), shelfLife: 3 },
  shoppingBag: { value: 'shoppingBag', label: 'Shopping Bag', icon: createStyledIcon(ShoppingBag), shelfLife: 7 },
  shoppingCart: { value: 'shoppingCart', label: 'Shopping Cart', icon: createStyledIcon(ShoppingCart), shelfLife: 7 },
  shrimp: { value: 'shrimp', label: 'Shrimp', icon: createStyledIcon(Shrimp), shelfLife: 2 },
  soap: { value: 'soap', label: 'Soap', icon: createStyledIcon(Circle), shelfLife: 365 },
  soupBowl: { value: 'soupBowl', label: 'Soup Bowl', icon: createStyledIcon(Soup), shelfLife: 3 },
  soy: { value: 'soy', label: 'Soy', icon: createStyledIcon(Bean), shelfLife: 365 },
  soyMilk: { value: 'soyMilk', label: 'Soy Milk', icon: createStyledIcon(Milk), shelfLife: 10 },
  spice: { value: 'spice', label: 'Spice', icon: createStyledIcon(Circle), shelfLife: 365 },
  spiceRack: { value: 'spiceRack', label: 'Spice Rack', icon: createStyledIcon(Circle), shelfLife: 365 },
  spinach: { value: 'spinach', label: 'Spinach', icon: createStyledIcon(Salad), shelfLife: 5 },
  spoon: { value: 'spoon', label: 'Spoon', icon: createStyledIcon(UtensilsCrossed), shelfLife: 7 },
  starfruit: { value: 'starfruit', label: 'Starfruit', icon: createStyledIcon(Star), shelfLife: 5 },
  stirFry: { value: 'stirFry', label: 'Stir Fry', icon: createStyledIcon(Beef), shelfLife: 3 },
  strawberry: { value: 'strawberry', label: 'Strawberry', icon: createStyledIcon(Cherry), shelfLife: 5 },
  stuffed: { value: 'stuffed', label: 'Stuffed', icon: createStyledIcon(Store), shelfLife: 3 },
  sunflower: { value: 'sunflower', label: 'Sunflower', icon: createStyledIcon(Flower), shelfLife: 7 },
  sushi: { value: 'sushi', label: 'Sushi', icon: createStyledIcon(Circle), shelfLife: 1 },
  sushiRoll: { value: 'sushiRoll', label: 'Sushi Roll', icon: createStyledIcon(Circle), shelfLife: 1 },
  tea: { value: 'tea', label: 'Tea', icon: createStyledIcon(Coffee), shelfLife: 180 },
  teaCup: { value: 'teaCup', label: 'Tea Cup', icon: createStyledIcon(Coffee), shelfLife: 1 },
  tomatoSauce: { value: 'tomatoSauce', label: 'Tomato Sauce', icon: createStyledIcon(CircleAlert), shelfLife: 14 },
  tomato: { value: 'tomato', label: 'Tomato', icon: createStyledIcon(Cherry), shelfLife: 7 },
  tomatoSlice: { value: 'tomatoSlice', label: 'Tomato Slice', icon: createStyledIcon(Cherry), shelfLife: 3 },
  toothPaste: { value: 'toothPaste', label: 'Toothpaste', icon: createStyledIcon(ZoomIn), shelfLife: 730 },
  trash: { value: 'trash', label: 'Trash', icon: createStyledIcon(Trash), shelfLife: 7 },
  tuna: { value: 'tuna', label: 'Tuna', icon: createStyledIcon(Fish), shelfLife: 3 },
  utensils: { value: 'utensils', label: 'Utensils', icon: createStyledIcon(UtensilsCrossed), shelfLife: 7 },
  utensilsCrossed: { value: 'utensilsCrossed', label: 'Utensils Crossed', icon: createStyledIcon(UtensilsCrossed), shelfLife: 7 },
  vegan: { value: 'vegan', label: 'Vegan', icon: createStyledIcon(Salad), shelfLife: 7 },
  vegetable: { value: 'vegetable', label: 'Vegetable', icon: createStyledIcon(Salad), shelfLife: 7 },
  walnut: { value: 'walnut', label: 'Walnut', icon: createStyledIcon(Circle), shelfLife: 180 },
  wash: { value: 'wash', label: 'Wash', icon: createStyledIcon(Droplets), shelfLife: 7 },
  waterBottle: { value: 'waterBottle', label: 'Water Bottle', icon: createStyledIcon(Bottle), shelfLife: 30 },
  waterDrop: { value: 'waterDrop', label: 'Water Drop', icon: createStyledIcon(Droplet), shelfLife: 7 },
  waterGlass: { value: 'waterGlass', label: 'Water Glass', icon: createStyledIcon(Circle), shelfLife: 1 },
  watermelon: { value: 'watermelon', label: 'Watermelon', icon: createStyledIcon(Circle), shelfLife: 7 },
  wheat: { value: 'wheat', label: 'Wheat', icon: createStyledIcon(Wheat), shelfLife: 365 },
  whiskey: { value: 'whiskey', label: 'Whiskey', icon: createStyledIcon(Circle), shelfLife: 365 },
  whiteBread: { value: 'whiteBread', label: 'White Bread', icon: createStyledIcon(BookOpen), shelfLife: 5 },
  whiteChocolate: { value: 'whiteChocolate', label: 'White Chocolate', icon: createStyledIcon(Cookie), shelfLife: 180 },
  wine: { value: 'wine', label: 'Wine', icon: createStyledIcon(Wine), shelfLife: 7 },
  wineGlass: { value: 'wineGlass', label: 'Wine Glass', icon: createStyledIcon(Wine), shelfLife: 7 },
  yogurt: { value: 'yogurt', label: 'Yogurt', icon: createStyledIcon(Soup), shelfLife: 14 }
};

// Default selected icons (initial state)
export const DEFAULT_SELECTED_ICONS = [
  'milk', 'coffee', 'apple', 'egg', 'banana', 'trash', 
  'box', 'cookie', 'cheese', 'tomato', 'tomatoSauce', 'filter'
];
