
import React from 'react';
import { 
  Apple, Banana, Beer, Beef, Cake, CircleAlert, Carrot, Cherry, Coffee, Cookie, Croissant, Droplet,
  Drumstick, Egg, Fish, IceCream, Milk, Pizza, Salad, Sandwich, Wine, Box, Trash,
  ChevronDown, Filter, FlaskConical as Flask, Circle as LemonIcon, Grape as GrapeIcon, Circle as OrangeIcon, 
  Bookmark as BreadIcon, Circle as SaltIcon, Circle as PepperIcon, 
  Martini, BowlFood as BowlIcon, Baby, Axe, BookOpen, Flame as FlameKindling, Bookmark, BookPlus, Cactus as CactusIcon, Calculator, 
  Calendar, CandlestickChart as Candlestick, Candy, Cake as CakeIcon, IceCream as IceCreamIcon, Bus, Package,
  QrCode as CerealIcon, Cat, ChefHat as Chef, ChevronRight, Eye as ChocolateIcon, Gift as CherryIcon, Heart as ChiliIcon, 
  CircleEllipsis, CircleDot, CirclePlus, Clock as CinnamonIcon, ClipboardList, Clock, Clock as ClockIcon, CloudFog, Cloud as CloudIcon, Cookie as CookieIcon,
  Cloud, Cloud as CloudRainIcon, Coffee as CoffeeIcon, CupSoda as CoffeeIcon2, Cog, Command, Compass, Contact, Container,
  Soup as CookingPotIcon, Copy, Copyright, Wheat as CornIcon, Sandwich as CrackerIcon, Crop, CreditCard, Crown, Map as DessertIcon,
  Diamond, Dice1, Donut, Droplets, EggFried, Eye, Factory, Hamburger as FastFoodIcon, Film, FilterX as MintIcon,
  Fish as SalmonIcon, Fish as TunaIcon, Fish as FishIcon, Ship as FishingRodIcon, 
  Wheat as FlourIcon, Flower as FlowerIcon, FolderIcon, FolderArchive, FolderDown,
  FolderLock, Footprints, Utensils as ForkIcon, UtensilsCrossed as FriesIcon, 
  Snowflake as FrozenIcon, Apple as FruitIcon, Fuel,
  Sprout as GardenIcon, Sprout, Circle as GarlicIcon, Gift, Gift as GiftIcon, 
  Flower as GingerIcon, Circle as GingerbreadIcon, 
  Circle as GlassIcon, Glasses as GlassWaterIcon, Wine as GlassWineIcon, Globe, Globe as GlobeIcon, Wheat as GrainIcon, 
  GrapeIcon as GrapeClusterIcon, Citrus as GrapefruitIcon, Bean as GreenBeansIcon, Leaf as GreenOnionIcon,
  Flame as GrilledIcon, Cat as HatIcon, Chef as ChefHatIcon,
  Heart as HerbIcon, Leaf as HerbsIcon, Bell as HotelBellIcon, Flame as HotIcon, Sandwich as HotDogIcon,
  IceCream as IceCreamScoopIcon, Martini as IceCreamShakeIcon, Image, Inbox, IndentDecrease, IndianRupee, Pumpkin as PumpkinIcon,
  Circle as JamJarIcon, Car as JarIcon, Soup as JelloBowlIcon, Coffee as JugIcon, 
  UtensilsCrossed as KebabIcon, Circle as KetchupIcon, Cherry as KiwiIcon, Circle as KnifeIcon, Scissors as KnifeIcon2,
  Layers as LayerIcon, Layers, Circle as LemonSliceIcon, Salad as LettuceIcon, Timer as LimeIcon, 
  Circle as LiquidsoapIcon, Fish as LobsterIcon,
  Lock as LockedIcon, Cookie as MacaronIcon, User as ManIcon, Circle as MandarinIcon, Circle as MangoIcon, Store as MarketIcon, 
  Store as GroceryIcon, Target as MarsIcon, Candy as MarshmallowIcon,
  Maximize, Medal, Circle as MelonIcon, Menu, MessageCircle, Mic, Milk as MilkBottleIcon, Minimize, 
  Flower as MintLeafIcon, UtensilsCrossed as MixingBowlIcon,
  Moon as MoonIcon, Moon, MoreHorizontal, MousePointer, Circle as MushroomIcon, Dumbbell, Music, Navigation, Egg as NestingDollsIcon, Network,
  Newspaper, FileText as NotepadTextIcon, Notebook, Nut as NutIcon, Beef as NutritionIcon, Wheat as OatsIcon, Octagon, Circle as OliveOilIcon, 
  Citrus as OliveIcon, CircleDot as OnionIcon,
  CircleDot as OnionIcon2, Circle as OrangeSliceIcon, Circle as OvenIcon, Box as OvenIcon2, PaintBucket, Paintbrush, Palette, Pizza as PancakeIcon, 
  Layers as PancakesIcon,
  Flower as PaprikaIcon, Circle as PastaIcon, Sandwich as PastaIcon2, Circle as PeachIcon, Circle as PearIcon, Circle as PearIcon2, 
  Pen, Circle as PepperShakerIcon, Flower as PeppermintIcon, Percent,
  Phone, PictureInPicture, Circle as PieIcon, PieChart, PieChart as PieIcon2, Pill, Pin, Package as PickleJarIcon, Circle as PineappleIcon, 
  Pizza as PizzaSliceIcon,
  Loader as PlaceholderIcon, Plane, CalendarDays as PlanningIcon, Sprout as PlantIcon, Plant as Plant2Icon, Flower as PlantPotIcon, 
  Play, Cherry as PlumIcon, Plus, Pocket,
  Circle as PopcornIcon, Circle as PopsicleIcon, Soup as PotIcon, Soup as PotIcon2, Flower as PotFlowerIcon, CircleDot as PotatoIcon, 
  CircleDot as PotatoesIcon, PoundSterling, Shrimp as PrawnIcon, Circle as PretzelIcon,
  Printer, Projector, Dumbbell as ProteinIcon, Martini as ProteinShakeIcon, 
  Circle as CannedPumpkinIcon, Circle as PumpkinIcon2, Puzzle, QrCode, Quote, Circle as RabbitIcon,
  Radio, CircleDot as RadishIcon, Radio as RadioIcon, Receipt, Dumbbell as RecipeBoxIcon, 
  Recycle, Redo, RefreshCw, Regex, Repeat,
  Reply, UtensilsCrossed as RestaurantIcon, Rewind, Ribbon, Wheat as RiceIcon, Sandwich as RiceBallIcon, 
  Soup as RiceBowlIcon, Rocket, RotateCw, Route,
  Router, Rss, Ruler, Running as RunningIcon, Martini as RumIcon, Flower as SageIcon, 
  Circle as SaltShakerIcon, Scale, Scissors, ScreenShare,
  Search, Shield as SecurityIcon, Send, Server, Settings, Share, Shield, ShoppingBag, ShoppingCart, Shovel,
  Shrimp as ShrimpIcon, Shrink, Shuffle, Sidebar, Sigma, Signal, SkipBack, SkipForward, Skull,
  Pizza as SliceIcon, SlidersHorizontal, Smartphone, SmilePlus as SmileIcon, Smile as SmilieIcon, 
  IceCream as SnowconeIcon, Snowflake, Sofa, SortAsc, SortDesc,
  Soup as SoupBowlIcon, Bean as SoyIcon, Milk as SoyMilkIcon, Flower as SpaIcon, Speaker, SpellCheck, 
  Circle as SpiceIcon, Circle as SpiceRackIcon, Salad as SpinachIcon,
  UtensilsCrossed as SpoonIcon, UtensilsCrossed as SpoonKnifeIcon, Square, Users as StaffIcon, Star, 
  Star as StarfruitIcon, Beef as StirFryIcon, Footprints as StoolIcon, StopCircle, Store,
  Cherry as StrawberryIcon, Store as StuffedIcon, Suitcase, Sun, Flower as SunflowerIcon, 
  Headphones as SupportIcon, Circle as SushiIcon, 
  Circle as SushiRollIcon, Table, LampFloor as TableLampIcon,
  Table as DiningTableIcon, Tag, Target, Coffee as TeaIcon, CupSoda as TeaCupIcon, Soup as KettleIcon, 
  Text, FileText as TextIcon, Thermometer,
  ThumbsDown, ThumbsUp, Ticket, Timer, Timer as TimerIcon, TimerOff, TimerReset, ToggleLeft, ToggleRight, Cherry as TomatoIcon,
  Tool, Cherry as TomatoSliceIcon, Tooth as ToothIcon, Toothbrush, Hat, Trophy, Truck, Tv, Twitch, Twitter,
  Umbrella, Underline, Undo, Unlink, Upload, User, Users, UtensilsCrossed, UtensilsCrossed as UtensilsIcon, Salad as VeganIcon,
  Salad as VegetableIcon, Video, Video as VideoIcon, Eye as ViewIcon, Voicemail, Volume, Wallet, Nut as WalnutIcon, 
  Droplets as WashIcon, WashingMachine,
  Watch, Bottle as WaterBottleIcon, Droplet as WaterDropIcon, Circle as WaterGlassIcon, Circle as WatermelonIcon, 
  Wave, WaveSine, Wave as WaveSawtoothIcon, 
  Square as WaveSquareIcon, Triangle as WaveTriangleIcon,
  Webcam, Wheat as WheatIcon, Circle as WhiskeyIcon, BookOpen as WhiteBreadIcon, Cookie as WhiteChocolateIcon, 
  Wifi, Wind, Wine as WineGlassIcon, Wrench, X,
  Dumbbell as YogaIcon, Soup as YogurtIcon, Youtube, Zap, ZoomIn, ZoomOut
} from "lucide-react";

// Create a simple icon component with consistent styling
export const createStyledIcon = (IconComponent: React.ComponentType<React.SVGProps<SVGSVGElement>>) => {
  return <IconComponent className="h-5 w-5" />;
};
